# Generated by Django 4.2.7 on 2023-12-09 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-creado'], 'verbose_name': 'noticia', 'verbose_name_plural': 'noticias'},
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='created',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='updated',
            new_name='modificado',
        ),
    ]
