# Generated by Django 3.2 on 2023-12-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_noticia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='modificado',
            field=models.DateTimeField(null=True),
        ),
    ]
