# Generated by Django 5.0 on 2023-12-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
