# Generated by Django 3.2 on 2023-12-26 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='Contactos',
        ),
    ]
