# Generated by Django 4.2.7 on 2023-12-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_rename_contacto_contactos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactos',
            options={'verbose_name_plural': 'Contactos'},
        ),
    ]
