# Generated by Django 4.2.7 on 2023-12-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_alter_contactos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactos',
            options={},
        ),
    ]
