# Generated by Django 4.2.7 on 2023-12-28 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0004_alter_contactos_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactos',
            new_name='Contacto',
        ),
    ]
