# Generated by Django 4.2.7 on 2023-12-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0005_rename_contactos_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
    ]
